/*******************************************************************************
 * Copyright (C) 2019 DSG at University of Athens
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mvconsensus.proto

package gr.uoa.di.dsg.consensus.multivalued.messages;

public final class MultiValueConsensusMessage {
  private MultiValueConsensusMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MVInitialOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MVInitial)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 2;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 2;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 3;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 3;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 4;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 4;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 5;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 6;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 6;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code MVInitial}
   */
  public static final class MVInitial extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MVInitial)
      MVInitialOrBuilder {
    // Use MVInitial.newBuilder() to construct.
    private MVInitial(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MVInitial(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MVInitial defaultInstance;
    public static MVInitial getDefaultInstance() {
      return defaultInstance;
    }

    public MVInitial getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MVInitial(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInitial_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInitial_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.Builder.class);
    }

    public static com.google.protobuf.Parser<MVInitial> PARSER =
        new com.google.protobuf.AbstractParser<MVInitial>() {
      public MVInitial parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MVInitial(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MVInitial> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 2;
    private int bid_;
    /**
     * <code>required int32 bid = 2;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 2;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 3;
    private int cid_;
    /**
     * <code>required int32 cid = 3;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 3;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 4;
    private int pid_;
    /**
     * <code>required int32 pid = 4;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 4;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 5;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 5;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 6;
    private java.lang.Object value_;
    /**
     * <code>required string value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 6;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MVInitial}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MVInitial)
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitialOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInitial_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInitial_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInitial_descriptor;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial getDefaultInstanceForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.getDefaultInstance();
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial build() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial buildPartial() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial result = new gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial) {
          return mergeFrom((gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial other) {
        if (other == gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitial) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 2;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 3;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 4;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 5;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 6;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MVInitial)
    }

    static {
      defaultInstance = new MVInitial(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MVInitial)
  }

  public interface MVInitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MVInit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 2;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 2;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 3;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 3;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 4;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 4;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 5;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 6;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 6;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code MVInit}
   */
  public static final class MVInit extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MVInit)
      MVInitOrBuilder {
    // Use MVInit.newBuilder() to construct.
    private MVInit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MVInit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MVInit defaultInstance;
    public static MVInit getDefaultInstance() {
      return defaultInstance;
    }

    public MVInit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MVInit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.Builder.class);
    }

    public static com.google.protobuf.Parser<MVInit> PARSER =
        new com.google.protobuf.AbstractParser<MVInit>() {
      public MVInit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MVInit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MVInit> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 2;
    private int bid_;
    /**
     * <code>required int32 bid = 2;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 2;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 3;
    private int cid_;
    /**
     * <code>required int32 cid = 3;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 3;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 4;
    private int pid_;
    /**
     * <code>required int32 pid = 4;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 4;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 5;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 5;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 6;
    private java.lang.Object value_;
    /**
     * <code>required string value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 6;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MVInit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MVInit)
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVInit_descriptor;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit getDefaultInstanceForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.getDefaultInstance();
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit build() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit buildPartial() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit result = new gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit) {
          return mergeFrom((gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit other) {
        if (other == gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVInit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 2;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 3;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 4;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 5;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 6;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MVInit)
    }

    static {
      defaultInstance = new MVInit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MVInit)
  }

  public interface MVVectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MVVector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 2;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 2;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 3;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 3;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 4;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 4;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 5;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 5;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 6;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 6;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>repeated string initValues = 7;</code>
     */
    com.google.protobuf.ProtocolStringList
        getInitValuesList();
    /**
     * <code>repeated string initValues = 7;</code>
     */
    int getInitValuesCount();
    /**
     * <code>repeated string initValues = 7;</code>
     */
    java.lang.String getInitValues(int index);
    /**
     * <code>repeated string initValues = 7;</code>
     */
    com.google.protobuf.ByteString
        getInitValuesBytes(int index);
  }
  /**
   * Protobuf type {@code MVVector}
   */
  public static final class MVVector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MVVector)
      MVVectorOrBuilder {
    // Use MVVector.newBuilder() to construct.
    private MVVector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MVVector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MVVector defaultInstance;
    public static MVVector getDefaultInstance() {
      return defaultInstance;
    }

    public MVVector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MVVector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                initValues_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              initValues_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          initValues_ = initValues_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVVector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.Builder.class);
    }

    public static com.google.protobuf.Parser<MVVector> PARSER =
        new com.google.protobuf.AbstractParser<MVVector>() {
      public MVVector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MVVector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MVVector> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 2;
    private int bid_;
    /**
     * <code>required int32 bid = 2;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 2;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 3;
    private int cid_;
    /**
     * <code>required int32 cid = 3;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 3;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 4;
    private int pid_;
    /**
     * <code>required int32 pid = 4;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 4;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 5;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 5;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 6;
    private java.lang.Object value_;
    /**
     * <code>required string value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 6;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 6;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITVALUES_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList initValues_;
    /**
     * <code>repeated string initValues = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInitValuesList() {
      return initValues_;
    }
    /**
     * <code>repeated string initValues = 7;</code>
     */
    public int getInitValuesCount() {
      return initValues_.size();
    }
    /**
     * <code>repeated string initValues = 7;</code>
     */
    public java.lang.String getInitValues(int index) {
      return initValues_.get(index);
    }
    /**
     * <code>repeated string initValues = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInitValuesBytes(int index) {
      return initValues_.getByteString(index);
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
      initValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getValueBytes());
      }
      for (int i = 0; i < initValues_.size(); i++) {
        output.writeBytes(7, initValues_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getValueBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < initValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(initValues_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getInitValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MVVector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MVVector)
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVVector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.class, gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        initValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.internal_static_MVVector_descriptor;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector getDefaultInstanceForType() {
        return gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.getDefaultInstance();
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector build() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector buildPartial() {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector result = new gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          initValues_ = initValues_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.initValues_ = initValues_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector) {
          return mergeFrom((gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector other) {
        if (other == gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        if (!other.initValues_.isEmpty()) {
          if (initValues_.isEmpty()) {
            initValues_ = other.initValues_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureInitValuesIsMutable();
            initValues_.addAll(other.initValues_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.consensus.multivalued.messages.MultiValueConsensusMessage.MVVector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 2;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 2;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 3;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 3;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 4;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 5;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 5;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 6;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 6;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList initValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInitValuesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          initValues_ = new com.google.protobuf.LazyStringArrayList(initValues_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInitValuesList() {
        return initValues_.getUnmodifiableView();
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public int getInitValuesCount() {
        return initValues_.size();
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public java.lang.String getInitValues(int index) {
        return initValues_.get(index);
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInitValuesBytes(int index) {
        return initValues_.getByteString(index);
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public Builder setInitValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInitValuesIsMutable();
        initValues_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public Builder addInitValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInitValuesIsMutable();
        initValues_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public Builder addAllInitValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureInitValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, initValues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public Builder clearInitValues() {
        initValues_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string initValues = 7;</code>
       */
      public Builder addInitValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInitValuesIsMutable();
        initValues_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MVVector)
    }

    static {
      defaultInstance = new MVVector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MVVector)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MVInitial_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MVInitial_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MVInit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MVInit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MVVector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MVVector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021mvconsensus.proto\"O\n\tMVInitial\022\013\n\003bid\030" +
      "\002 \002(\005\022\013\n\003cid\030\003 \002(\005\022\013\n\003pid\030\004 \002(\005\022\014\n\004icid\030" +
      "\005 \002(\t\022\r\n\005value\030\006 \002(\t\"L\n\006MVInit\022\013\n\003bid\030\002 " +
      "\002(\005\022\013\n\003cid\030\003 \002(\005\022\013\n\003pid\030\004 \002(\005\022\014\n\004icid\030\005 " +
      "\002(\t\022\r\n\005value\030\006 \002(\t\"b\n\010MVVector\022\013\n\003bid\030\002 " +
      "\002(\005\022\013\n\003cid\030\003 \002(\005\022\013\n\003pid\030\004 \002(\005\022\014\n\004icid\030\005 " +
      "\002(\t\022\r\n\005value\030\006 \002(\t\022\022\n\ninitValues\030\007 \003(\tBJ" +
      "\n,gr.uoa.di.dsg.consensus.multivalued.me" +
      "ssagesB\032MultiValueConsensusMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MVInitial_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MVInitial_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MVInitial_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", });
    internal_static_MVInit_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MVInit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MVInit_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", });
    internal_static_MVVector_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MVVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MVVector_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", "InitValues", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
