/*******************************************************************************
 * Copyright (C) 2019 DSG at University of Athens
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: synchronousIC.proto

package gr.uoa.di.dsg.ic.lamport;

public final class InteractiveConsistencyMessage {
  private InteractiveConsistencyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ICInitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ICInit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string icid = 2;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 2;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 2;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required int32 round = 3;</code>
     */
    boolean hasRound();
    /**
     * <code>required int32 round = 3;</code>
     */
    int getRound();

    /**
     * <code>required int32 pid = 4;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 4;</code>
     */
    int getPid();

    /**
     * <code>required string value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code ICInit}
   */
  public static final class ICInit extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ICInit)
      ICInitOrBuilder {
    // Use ICInit.newBuilder() to construct.
    private ICInit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ICInit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ICInit defaultInstance;
    public static ICInit getDefaultInstance() {
      return defaultInstance;
    }

    public ICInit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ICInit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              icid_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              round_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICInit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICInit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.class, gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.Builder.class);
    }

    public static com.google.protobuf.Parser<ICInit> PARSER =
        new com.google.protobuf.AbstractParser<ICInit>() {
      public ICInit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ICInit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ICInit> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ICID_FIELD_NUMBER = 2;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 2;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string icid = 2;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUND_FIELD_NUMBER = 3;
    private int round_;
    /**
     * <code>required int32 round = 3;</code>
     */
    public boolean hasRound() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 round = 3;</code>
     */
    public int getRound() {
      return round_;
    }

    public static final int PID_FIELD_NUMBER = 4;
    private int pid_;
    /**
     * <code>required int32 pid = 4;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 4;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private java.lang.Object value_;
    /**
     * <code>required string value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      icid_ = "";
      round_ = 0;
      pid_ = 0;
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRound()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getIcidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, round_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIcidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, round_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ICInit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ICInit)
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICInit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICInit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.class, gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        round_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICInit_descriptor;
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit getDefaultInstanceForType() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.getDefaultInstance();
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit build() {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit buildPartial() {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit result = new gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.round_ = round_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit) {
          return mergeFrom((gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit other) {
        if (other == gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit.getDefaultInstance()) return this;
        if (other.hasIcid()) {
          bitField0_ |= 0x00000001;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000008;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasRound()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICInit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 2;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        icid_ = value;
        onChanged();
        return this;
      }

      private int round_ ;
      /**
       * <code>required int32 round = 3;</code>
       */
      public boolean hasRound() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public Builder setRound(int value) {
        bitField0_ |= 0x00000002;
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public Builder clearRound() {
        bitField0_ = (bitField0_ & ~0x00000002);
        round_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 4;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ICInit)
    }

    static {
      defaultInstance = new ICInit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ICInit)
  }

  public interface ICVectorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ICVector)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string icid = 2;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 2;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 2;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required int32 round = 3;</code>
     */
    boolean hasRound();
    /**
     * <code>required int32 round = 3;</code>
     */
    int getRound();

    /**
     * <code>required int32 pid = 4;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 4;</code>
     */
    int getPid();

    /**
     * <code>repeated string values = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getValuesList();
    /**
     * <code>repeated string values = 5;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 5;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 5;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code ICVector}
   */
  public static final class ICVector extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ICVector)
      ICVectorOrBuilder {
    // Use ICVector.newBuilder() to construct.
    private ICVector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ICVector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ICVector defaultInstance;
    public static ICVector getDefaultInstance() {
      return defaultInstance;
    }

    public ICVector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ICVector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              icid_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              round_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              values_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICVector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.class, gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.Builder.class);
    }

    public static com.google.protobuf.Parser<ICVector> PARSER =
        new com.google.protobuf.AbstractParser<ICVector>() {
      public ICVector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ICVector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ICVector> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ICID_FIELD_NUMBER = 2;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 2;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string icid = 2;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUND_FIELD_NUMBER = 3;
    private int round_;
    /**
     * <code>required int32 round = 3;</code>
     */
    public boolean hasRound() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 round = 3;</code>
     */
    public int getRound() {
      return round_;
    }

    public static final int PID_FIELD_NUMBER = 4;
    private int pid_;
    /**
     * <code>required int32 pid = 4;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 4;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int VALUES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private void initFields() {
      icid_ = "";
      round_ = 0;
      pid_ = 0;
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRound()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getIcidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, round_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, pid_);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(5, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIcidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, round_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ICVector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ICVector)
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICVector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.class, gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        round_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.internal_static_ICVector_descriptor;
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector getDefaultInstanceForType() {
        return gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.getDefaultInstance();
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector build() {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector buildPartial() {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector result = new gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.round_ = round_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector) {
          return mergeFrom((gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector other) {
        if (other == gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector.getDefaultInstance()) return this;
        if (other.hasIcid()) {
          bitField0_ |= 0x00000001;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasRound()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.ic.lamport.InteractiveConsistencyMessage.ICVector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 2;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 2;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        icid_ = value;
        onChanged();
        return this;
      }

      private int round_ ;
      /**
       * <code>required int32 round = 3;</code>
       */
      public boolean hasRound() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public int getRound() {
        return round_;
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public Builder setRound(int value) {
        bitField0_ |= 0x00000002;
        round_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 round = 3;</code>
       */
      public Builder clearRound() {
        bitField0_ = (bitField0_ & ~0x00000002);
        round_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 4;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 4;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ICVector)
    }

    static {
      defaultInstance = new ICVector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ICVector)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ICInit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ICInit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ICVector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ICVector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023synchronousIC.proto\"A\n\006ICInit\022\014\n\004icid\030" +
      "\002 \002(\t\022\r\n\005round\030\003 \002(\005\022\013\n\003pid\030\004 \002(\005\022\r\n\005val" +
      "ue\030\005 \002(\t\"D\n\010ICVector\022\014\n\004icid\030\002 \002(\t\022\r\n\005ro" +
      "und\030\003 \002(\005\022\013\n\003pid\030\004 \002(\005\022\016\n\006values\030\005 \003(\tB9" +
      "\n\030gr.uoa.di.dsg.ic.lamportB\035InteractiveC" +
      "onsistencyMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ICInit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ICInit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ICInit_descriptor,
        new java.lang.String[] { "Icid", "Round", "Pid", "Value", });
    internal_static_ICVector_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ICVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ICVector_descriptor,
        new java.lang.String[] { "Icid", "Round", "Pid", "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
