/*******************************************************************************
 * Copyright (C) 2019 DSG at University of Athens
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic.proto

package gr.uoa.di.dsg.broadcast.bracha;

public final class BrachaBroadcastMessage {
  private BrachaBroadcastMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InitMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InitMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 1;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 1;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 2;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 3;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 3;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 4;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code InitMessage}
   */
  public static final class InitMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:InitMessage)
      InitMessageOrBuilder {
    // Use InitMessage.newBuilder() to construct.
    private InitMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InitMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InitMessage defaultInstance;
    public static InitMessage getDefaultInstance() {
      return defaultInstance;
    }

    public InitMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InitMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_InitMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_InitMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<InitMessage> PARSER =
        new com.google.protobuf.AbstractParser<InitMessage>() {
      public InitMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InitMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 1;
    private int bid_;
    /**
     * <code>required int32 bid = 1;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 1;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <code>required int32 cid = 2;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_;
    /**
     * <code>required int32 pid = 3;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 3;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 4;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 4;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private java.lang.Object value_;
    /**
     * <code>required string value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InitMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InitMessage)
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_InitMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_InitMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_InitMessage_descriptor;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage getDefaultInstanceForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.getDefaultInstance();
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage build() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage buildPartial() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage result = new gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage) {
          return mergeFrom((gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage other) {
        if (other == gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.InitMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 1;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 2;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 3;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 4;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InitMessage)
    }

    static {
      defaultInstance = new InitMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InitMessage)
  }

  public interface EchoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EchoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 1;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 1;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 2;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 3;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 3;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 4;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code EchoMessage}
   */
  public static final class EchoMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EchoMessage)
      EchoMessageOrBuilder {
    // Use EchoMessage.newBuilder() to construct.
    private EchoMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EchoMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EchoMessage defaultInstance;
    public static EchoMessage getDefaultInstance() {
      return defaultInstance;
    }

    public EchoMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EchoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_EchoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_EchoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<EchoMessage> PARSER =
        new com.google.protobuf.AbstractParser<EchoMessage>() {
      public EchoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EchoMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 1;
    private int bid_;
    /**
     * <code>required int32 bid = 1;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 1;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <code>required int32 cid = 2;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_;
    /**
     * <code>required int32 pid = 3;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 3;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 4;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 4;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private java.lang.Object value_;
    /**
     * <code>required string value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EchoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EchoMessage)
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_EchoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_EchoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_EchoMessage_descriptor;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage getDefaultInstanceForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.getDefaultInstance();
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage build() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage buildPartial() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage result = new gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage) {
          return mergeFrom((gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage other) {
        if (other == gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.EchoMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 1;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 2;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 3;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 4;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EchoMessage)
    }

    static {
      defaultInstance = new EchoMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EchoMessage)
  }

  public interface ReadyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bid = 1;</code>
     */
    boolean hasBid();
    /**
     * <code>required int32 bid = 1;</code>
     */
    int getBid();

    /**
     * <code>required int32 cid = 2;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <code>required int32 pid = 3;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 3;</code>
     */
    int getPid();

    /**
     * <code>required string icid = 4;</code>
     */
    boolean hasIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    java.lang.String getIcid();
    /**
     * <code>required string icid = 4;</code>
     */
    com.google.protobuf.ByteString
        getIcidBytes();

    /**
     * <code>required string value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 5;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code ReadyMessage}
   */
  public static final class ReadyMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReadyMessage)
      ReadyMessageOrBuilder {
    // Use ReadyMessage.newBuilder() to construct.
    private ReadyMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadyMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadyMessage defaultInstance;
    public static ReadyMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ReadyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pid_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              icid_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_ReadyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_ReadyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadyMessage> PARSER =
        new com.google.protobuf.AbstractParser<ReadyMessage>() {
      public ReadyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadyMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadyMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BID_FIELD_NUMBER = 1;
    private int bid_;
    /**
     * <code>required int32 bid = 1;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bid = 1;</code>
     */
    public int getBid() {
      return bid_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <code>required int32 cid = 2;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int PID_FIELD_NUMBER = 3;
    private int pid_;
    /**
     * <code>required int32 pid = 3;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pid = 3;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int ICID_FIELD_NUMBER = 4;
    private java.lang.Object icid_;
    /**
     * <code>required string icid = 4;</code>
     */
    public boolean hasIcid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public java.lang.String getIcid() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string icid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIcidBytes() {
      java.lang.Object ref = icid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private java.lang.Object value_;
    /**
     * <code>required string value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string value = 5;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bid_ = 0;
      cid_ = 0;
      pid_ = 0;
      icid_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIcid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getIcidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadyMessage)
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_ReadyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_ReadyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.class, gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        icid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.internal_static_ReadyMessage_descriptor;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage getDefaultInstanceForType() {
        return gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.getDefaultInstance();
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage build() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage buildPartial() {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage result = new gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.icid_ = icid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage) {
          return mergeFrom((gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage other) {
        if (other == gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage.getDefaultInstance()) return this;
        if (other.hasBid()) {
          setBid(other.getBid());
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasIcid()) {
          bitField0_ |= 0x00000008;
          icid_ = other.icid_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000010;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBid()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasIcid()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.broadcast.bracha.BrachaBroadcastMessage.ReadyMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bid_ ;
      /**
       * <code>required int32 bid = 1;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public int getBid() {
        return bid_;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder setBid(int value) {
        bitField0_ |= 0x00000001;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bid = 1;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = 0;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 2;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required int32 pid = 3;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000004;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 3;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object icid_ = "";
      /**
       * <code>required string icid = 4;</code>
       */
      public boolean hasIcid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public java.lang.String getIcid() {
        java.lang.Object ref = icid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIcidBytes() {
        java.lang.Object ref = icid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder clearIcid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        icid_ = getDefaultInstance().getIcid();
        onChanged();
        return this;
      }
      /**
       * <code>required string icid = 4;</code>
       */
      public Builder setIcidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        icid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string value = 5;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 5;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReadyMessage)
    }

    static {
      defaultInstance = new ReadyMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReadyMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InitMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InitMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EchoMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EchoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReadyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgeneric.proto\"Q\n\013InitMessage\022\013\n\003bid\030\001 " +
      "\002(\005\022\013\n\003cid\030\002 \002(\005\022\013\n\003pid\030\003 \002(\005\022\014\n\004icid\030\004 " +
      "\002(\t\022\r\n\005value\030\005 \002(\t\"Q\n\013EchoMessage\022\013\n\003bid" +
      "\030\001 \002(\005\022\013\n\003cid\030\002 \002(\005\022\013\n\003pid\030\003 \002(\005\022\014\n\004icid" +
      "\030\004 \002(\t\022\r\n\005value\030\005 \002(\t\"R\n\014ReadyMessage\022\013\n" +
      "\003bid\030\001 \002(\005\022\013\n\003cid\030\002 \002(\005\022\013\n\003pid\030\003 \002(\005\022\014\n\004" +
      "icid\030\004 \002(\t\022\r\n\005value\030\005 \002(\tB8\n\036gr.uoa.di.d" +
      "sg.broadcast.brachaB\026BrachaBroadcastMess" +
      "age"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_InitMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InitMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_InitMessage_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", });
    internal_static_EchoMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EchoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EchoMessage_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", });
    internal_static_ReadyMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReadyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReadyMessage_descriptor,
        new java.lang.String[] { "Bid", "Cid", "Pid", "Icid", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
