/*******************************************************************************
 * Copyright (C) 2019 DSG at University of Athens
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: icdatum.proto

package gr.uoa.di.dsg.ic.bracha;

public final class ICDatumMessage {
  private ICDatumMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ICChunkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ICChunk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 chunkId = 1;</code>
     */
    boolean hasChunkId();
    /**
     * <code>required int32 chunkId = 1;</code>
     */
    int getChunkId();

    /**
     * <code>required string appID = 2;</code>
     */
    boolean hasAppID();
    /**
     * <code>required string appID = 2;</code>
     */
    java.lang.String getAppID();
    /**
     * <code>required string appID = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppIDBytes();

    /**
     * <code>required bytes chunkData = 3;</code>
     */
    boolean hasChunkData();
    /**
     * <code>required bytes chunkData = 3;</code>
     */
    com.google.protobuf.ByteString getChunkData();
  }
  /**
   * Protobuf type {@code ICChunk}
   */
  public static final class ICChunk extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ICChunk)
      ICChunkOrBuilder {
    // Use ICChunk.newBuilder() to construct.
    private ICChunk(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ICChunk(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ICChunk defaultInstance;
    public static ICChunk getDefaultInstance() {
      return defaultInstance;
    }

    public ICChunk getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ICChunk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      
      @SuppressWarnings("unused")
      int mutable_bitField0_ = 0;
      
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              chunkId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              appID_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              chunkData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunk_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.Builder.class);
    }

    public static com.google.protobuf.Parser<ICChunk> PARSER =
        new com.google.protobuf.AbstractParser<ICChunk>() {
      public ICChunk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ICChunk(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ICChunk> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CHUNKID_FIELD_NUMBER = 1;
    private int chunkId_;
    /**
     * <code>required int32 chunkId = 1;</code>
     */
    public boolean hasChunkId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 chunkId = 1;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int APPID_FIELD_NUMBER = 2;
    private java.lang.Object appID_;
    /**
     * <code>required string appID = 2;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string appID = 2;</code>
     */
    public java.lang.String getAppID() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIDBytes() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString chunkData_;
    /**
     * <code>required bytes chunkData = 3;</code>
     */
    public boolean hasChunkData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes chunkData = 3;</code>
     */
    public com.google.protobuf.ByteString getChunkData() {
      return chunkData_;
    }

    private void initFields() {
      chunkId_ = 0;
      appID_ = "";
      chunkData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChunkId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChunkData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, chunkId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, chunkData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, chunkId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, chunkData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ICChunk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ICChunk)
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunk_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        chunkId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chunkData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunk_descriptor;
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk getDefaultInstanceForType() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.getDefaultInstance();
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk build() {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk buildPartial() {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk result = new gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chunkId_ = chunkId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chunkData_ = chunkData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk) {
          return mergeFrom((gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk other) {
        if (other == gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk.getDefaultInstance()) return this;
        if (other.hasChunkId()) {
          setChunkId(other.getChunkId());
        }
        if (other.hasAppID()) {
          bitField0_ |= 0x00000002;
          appID_ = other.appID_;
          onChanged();
        }
        if (other.hasChunkData()) {
          setChunkData(other.getChunkData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChunkId()) {
          
          return false;
        }
        if (!hasAppID()) {
          
          return false;
        }
        if (!hasChunkData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunk) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int chunkId_ ;
      /**
       * <code>required int32 chunkId = 1;</code>
       */
      public boolean hasChunkId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 chunkId = 1;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>required int32 chunkId = 1;</code>
       */
      public Builder setChunkId(int value) {
        bitField0_ |= 0x00000001;
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chunkId = 1;</code>
       */
      public Builder clearChunkId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object appID_ = "";
      /**
       * <code>required string appID = 2;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string appID = 2;</code>
       */
      public java.lang.String getAppID() {
        java.lang.Object ref = appID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppIDBytes() {
        java.lang.Object ref = appID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appID = 2;</code>
       */
      public Builder setAppID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appID = 2;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appID_ = getDefaultInstance().getAppID();
        onChanged();
        return this;
      }
      /**
       * <code>required string appID = 2;</code>
       */
      public Builder setAppIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chunkData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes chunkData = 3;</code>
       */
      public boolean hasChunkData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes chunkData = 3;</code>
       */
      public com.google.protobuf.ByteString getChunkData() {
        return chunkData_;
      }
      /**
       * <code>required bytes chunkData = 3;</code>
       */
      public Builder setChunkData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        chunkData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes chunkData = 3;</code>
       */
      public Builder clearChunkData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkData_ = getDefaultInstance().getChunkData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ICChunk)
    }

    static {
      defaultInstance = new ICChunk(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ICChunk)
  }

  public interface ICChunkRecoveryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ICChunkRecovery)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string appID = 1;</code>
     */
    boolean hasAppID();
    /**
     * <code>required string appID = 1;</code>
     */
    java.lang.String getAppID();
    /**
     * <code>required string appID = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIDBytes();

    /**
     * <code>required int32 cid = 2;</code>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 2;</code>
     */
    int getCid();

    /**
     * <code>required int32 chunkId = 3;</code>
     */
    boolean hasChunkId();
    /**
     * <code>required int32 chunkId = 3;</code>
     */
    int getChunkId();

    /**
     * <code>required bytes chunkData = 4;</code>
     */
    boolean hasChunkData();
    /**
     * <code>required bytes chunkData = 4;</code>
     */
    com.google.protobuf.ByteString getChunkData();

    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> 
        getSignatureList();
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple getSignature(int index);
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    int getSignatureCount();
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    java.util.List<? extends gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder> 
        getSignatureOrBuilderList();
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder getSignatureOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ICChunkRecovery}
   */
  public static final class ICChunkRecovery extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ICChunkRecovery)
      ICChunkRecoveryOrBuilder {
    // Use ICChunkRecovery.newBuilder() to construct.
    private ICChunkRecovery(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ICChunkRecovery(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ICChunkRecovery defaultInstance;
    public static ICChunkRecovery getDefaultInstance() {
      return defaultInstance;
    }

    public ICChunkRecovery getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ICChunkRecovery(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              appID_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cid_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              chunkId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              chunkData_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                signature_ = new java.util.ArrayList<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple>();
                mutable_bitField0_ |= 0x00000010;
              }
              signature_.add(input.readMessage(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          signature_ = java.util.Collections.unmodifiableList(signature_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.Builder.class);
    }

    public static com.google.protobuf.Parser<ICChunkRecovery> PARSER =
        new com.google.protobuf.AbstractParser<ICChunkRecovery>() {
      public ICChunkRecovery parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ICChunkRecovery(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ICChunkRecovery> getParserForType() {
      return PARSER;
    }

    public interface OwnerAndSignatureTupleOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ICChunkRecovery.OwnerAndSignatureTuple)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 owner = 1;</code>
       */
      boolean hasOwner();
      /**
       * <code>required int32 owner = 1;</code>
       */
      int getOwner();

      /**
       * <code>required bytes signature = 2;</code>
       */
      boolean hasSignature();
      /**
       * <code>required bytes signature = 2;</code>
       */
      com.google.protobuf.ByteString getSignature();
    }
    /**
     * Protobuf type {@code ICChunkRecovery.OwnerAndSignatureTuple}
     */
    public static final class OwnerAndSignatureTuple extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ICChunkRecovery.OwnerAndSignatureTuple)
        OwnerAndSignatureTupleOrBuilder {
      // Use OwnerAndSignatureTuple.newBuilder() to construct.
      private OwnerAndSignatureTuple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private OwnerAndSignatureTuple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final OwnerAndSignatureTuple defaultInstance;
      public static OwnerAndSignatureTuple getDefaultInstance() {
        return defaultInstance;
      }

      public OwnerAndSignatureTuple getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private OwnerAndSignatureTuple(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        
        @SuppressWarnings("unused")
        int mutable_bitField0_ = 0;
        
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                owner_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                signature_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_OwnerAndSignatureTuple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder.class);
      }

      public static com.google.protobuf.Parser<OwnerAndSignatureTuple> PARSER =
          new com.google.protobuf.AbstractParser<OwnerAndSignatureTuple>() {
        public OwnerAndSignatureTuple parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new OwnerAndSignatureTuple(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<OwnerAndSignatureTuple> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int OWNER_FIELD_NUMBER = 1;
      private int owner_;
      /**
       * <code>required int32 owner = 1;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 owner = 1;</code>
       */
      public int getOwner() {
        return owner_;
      }

      public static final int SIGNATURE_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString signature_;
      /**
       * <code>required bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }

      private void initFields() {
        owner_ = 0;
        signature_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasOwner()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSignature()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, owner_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, signature_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, owner_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, signature_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ICChunkRecovery.OwnerAndSignatureTuple}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ICChunkRecovery.OwnerAndSignatureTuple)
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_OwnerAndSignatureTuple_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder.class);
        }

        // Construct using gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          owner_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          signature_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor;
        }

        public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple getDefaultInstanceForType() {
          return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.getDefaultInstance();
        }

        public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple build() {
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple buildPartial() {
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple result = new gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.owner_ = owner_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.signature_ = signature_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple) {
            return mergeFrom((gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple other) {
          if (other == gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.getDefaultInstance()) return this;
          if (other.hasOwner()) {
            setOwner(other.getOwner());
          }
          if (other.hasSignature()) {
            setSignature(other.getSignature());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasOwner()) {
            
            return false;
          }
          if (!hasSignature()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int owner_ ;
        /**
         * <code>required int32 owner = 1;</code>
         */
        public boolean hasOwner() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 owner = 1;</code>
         */
        public int getOwner() {
          return owner_;
        }
        /**
         * <code>required int32 owner = 1;</code>
         */
        public Builder setOwner(int value) {
          bitField0_ |= 0x00000001;
          owner_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 owner = 1;</code>
         */
        public Builder clearOwner() {
          bitField0_ = (bitField0_ & ~0x00000001);
          owner_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes signature = 2;</code>
         */
        public boolean hasSignature() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required bytes signature = 2;</code>
         */
        public com.google.protobuf.ByteString getSignature() {
          return signature_;
        }
        /**
         * <code>required bytes signature = 2;</code>
         */
        public Builder setSignature(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          signature_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes signature = 2;</code>
         */
        public Builder clearSignature() {
          bitField0_ = (bitField0_ & ~0x00000002);
          signature_ = getDefaultInstance().getSignature();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ICChunkRecovery.OwnerAndSignatureTuple)
      }

      static {
        defaultInstance = new OwnerAndSignatureTuple(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ICChunkRecovery.OwnerAndSignatureTuple)
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private java.lang.Object appID_;
    /**
     * <code>required string appID = 1;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string appID = 1;</code>
     */
    public java.lang.String getAppID() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIDBytes() {
      java.lang.Object ref = appID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CID_FIELD_NUMBER = 2;
    private int cid_;
    /**
     * <code>required int32 cid = 2;</code>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cid = 2;</code>
     */
    public int getCid() {
      return cid_;
    }

    public static final int CHUNKID_FIELD_NUMBER = 3;
    private int chunkId_;
    /**
     * <code>required int32 chunkId = 3;</code>
     */
    public boolean hasChunkId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 chunkId = 3;</code>
     */
    public int getChunkId() {
      return chunkId_;
    }

    public static final int CHUNKDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString chunkData_;
    /**
     * <code>required bytes chunkData = 4;</code>
     */
    public boolean hasChunkData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes chunkData = 4;</code>
     */
    public com.google.protobuf.ByteString getChunkData() {
      return chunkData_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 5;
    private java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> signature_;
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    public java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> getSignatureList() {
      return signature_;
    }
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    public java.util.List<? extends gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder> 
        getSignatureOrBuilderList() {
      return signature_;
    }
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    public int getSignatureCount() {
      return signature_.size();
    }
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple getSignature(int index) {
      return signature_.get(index);
    }
    /**
     * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
     */
    public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder getSignatureOrBuilder(
        int index) {
      return signature_.get(index);
    }

    private void initFields() {
      appID_ = "";
      cid_ = 0;
      chunkId_ = 0;
      chunkData_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChunkId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChunkData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSignatureCount(); i++) {
        if (!getSignature(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAppIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, chunkId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, chunkData_);
      }
      for (int i = 0; i < signature_.size(); i++) {
        output.writeMessage(5, signature_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAppIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chunkId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, chunkData_);
      }
      for (int i = 0; i < signature_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, signature_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ICChunkRecovery}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ICChunkRecovery)
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecoveryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.class, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.Builder.class);
      }

      // Construct using gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSignatureFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        appID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chunkId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (signatureBuilder_ == null) {
          signature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          signatureBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.internal_static_ICChunkRecovery_descriptor;
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery getDefaultInstanceForType() {
        return gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.getDefaultInstance();
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery build() {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery buildPartial() {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery result = new gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chunkId_ = chunkId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chunkData_ = chunkData_;
        if (signatureBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            signature_ = java.util.Collections.unmodifiableList(signature_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.signature_ = signature_;
        } else {
          result.signature_ = signatureBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery) {
          return mergeFrom((gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery other) {
        if (other == gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.getDefaultInstance()) return this;
        if (other.hasAppID()) {
          bitField0_ |= 0x00000001;
          appID_ = other.appID_;
          onChanged();
        }
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasChunkId()) {
          setChunkId(other.getChunkId());
        }
        if (other.hasChunkData()) {
          setChunkData(other.getChunkData());
        }
        if (signatureBuilder_ == null) {
          if (!other.signature_.isEmpty()) {
            if (signature_.isEmpty()) {
              signature_ = other.signature_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureSignatureIsMutable();
              signature_.addAll(other.signature_);
            }
            onChanged();
          }
        } else {
          if (!other.signature_.isEmpty()) {
            if (signatureBuilder_.isEmpty()) {
              signatureBuilder_.dispose();
              signatureBuilder_ = null;
              signature_ = other.signature_;
              bitField0_ = (bitField0_ & ~0x00000010);
              signatureBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSignatureFieldBuilder() : null;
            } else {
              signatureBuilder_.addAllMessages(other.signature_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppID()) {
          
          return false;
        }
        if (!hasCid()) {
          
          return false;
        }
        if (!hasChunkId()) {
          
          return false;
        }
        if (!hasChunkData()) {
          
          return false;
        }
        for (int i = 0; i < getSignatureCount(); i++) {
          if (!getSignature(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appID_ = "";
      /**
       * <code>required string appID = 1;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string appID = 1;</code>
       */
      public java.lang.String getAppID() {
        java.lang.Object ref = appID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIDBytes() {
        java.lang.Object ref = appID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appID = 1;</code>
       */
      public Builder setAppID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appID = 1;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appID_ = getDefaultInstance().getAppID();
        onChanged();
        return this;
      }
      /**
       * <code>required string appID = 1;</code>
       */
      public Builder setAppIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appID_ = value;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>required int32 cid = 2;</code>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000002;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 2;</code>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cid_ = 0;
        onChanged();
        return this;
      }

      private int chunkId_ ;
      /**
       * <code>required int32 chunkId = 3;</code>
       */
      public boolean hasChunkId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 chunkId = 3;</code>
       */
      public int getChunkId() {
        return chunkId_;
      }
      /**
       * <code>required int32 chunkId = 3;</code>
       */
      public Builder setChunkId(int value) {
        bitField0_ |= 0x00000004;
        chunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 chunkId = 3;</code>
       */
      public Builder clearChunkId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chunkId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString chunkData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes chunkData = 4;</code>
       */
      public boolean hasChunkData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes chunkData = 4;</code>
       */
      public com.google.protobuf.ByteString getChunkData() {
        return chunkData_;
      }
      /**
       * <code>required bytes chunkData = 4;</code>
       */
      public Builder setChunkData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chunkData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes chunkData = 4;</code>
       */
      public Builder clearChunkData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chunkData_ = getDefaultInstance().getChunkData();
        onChanged();
        return this;
      }

      private java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> signature_ =
        java.util.Collections.emptyList();
      private void ensureSignatureIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          signature_ = new java.util.ArrayList<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple>(signature_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder> signatureBuilder_;

      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> getSignatureList() {
        if (signatureBuilder_ == null) {
          return java.util.Collections.unmodifiableList(signature_);
        } else {
          return signatureBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public int getSignatureCount() {
        if (signatureBuilder_ == null) {
          return signature_.size();
        } else {
          return signatureBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple getSignature(int index) {
        if (signatureBuilder_ == null) {
          return signature_.get(index);
        } else {
          return signatureBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder setSignature(
          int index, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignatureIsMutable();
          signature_.set(index, value);
          onChanged();
        } else {
          signatureBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder setSignature(
          int index, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          ensureSignatureIsMutable();
          signature_.set(index, builderForValue.build());
          onChanged();
        } else {
          signatureBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder addSignature(gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignatureIsMutable();
          signature_.add(value);
          onChanged();
        } else {
          signatureBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder addSignature(
          int index, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple value) {
        if (signatureBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignatureIsMutable();
          signature_.add(index, value);
          onChanged();
        } else {
          signatureBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder addSignature(
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          ensureSignatureIsMutable();
          signature_.add(builderForValue.build());
          onChanged();
        } else {
          signatureBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder addSignature(
          int index, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder builderForValue) {
        if (signatureBuilder_ == null) {
          ensureSignatureIsMutable();
          signature_.add(index, builderForValue.build());
          onChanged();
        } else {
          signatureBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder addAllSignature(
          java.lang.Iterable<? extends gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple> values) {
        if (signatureBuilder_ == null) {
          ensureSignatureIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, signature_);
          onChanged();
        } else {
          signatureBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder clearSignature() {
        if (signatureBuilder_ == null) {
          signature_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          signatureBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public Builder removeSignature(int index) {
        if (signatureBuilder_ == null) {
          ensureSignatureIsMutable();
          signature_.remove(index);
          onChanged();
        } else {
          signatureBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder getSignatureBuilder(
          int index) {
        return getSignatureFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder getSignatureOrBuilder(
          int index) {
        if (signatureBuilder_ == null) {
          return signature_.get(index);  } else {
          return signatureBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public java.util.List<? extends gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder> 
           getSignatureOrBuilderList() {
        if (signatureBuilder_ != null) {
          return signatureBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(signature_);
        }
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder addSignatureBuilder() {
        return getSignatureFieldBuilder().addBuilder(
            gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.getDefaultInstance());
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder addSignatureBuilder(
          int index) {
        return getSignatureFieldBuilder().addBuilder(
            index, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.getDefaultInstance());
      }
      /**
       * <code>repeated .ICChunkRecovery.OwnerAndSignatureTuple signature = 5;</code>
       */
      public java.util.List<gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder> 
           getSignatureBuilderList() {
        return getSignatureFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder> 
          getSignatureFieldBuilder() {
        if (signatureBuilder_ == null) {
          signatureBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTuple.Builder, gr.uoa.di.dsg.ic.bracha.ICDatumMessage.ICChunkRecovery.OwnerAndSignatureTupleOrBuilder>(
                  signature_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          signature_ = null;
        }
        return signatureBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ICChunkRecovery)
    }

    static {
      defaultInstance = new ICChunkRecovery(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ICChunkRecovery)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ICChunk_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ICChunk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ICChunkRecovery_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ICChunkRecovery_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ICChunkRecovery_OwnerAndSignatureTuple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ricdatum.proto\"<\n\007ICChunk\022\017\n\007chunkId\030\001 " +
      "\002(\005\022\r\n\005appID\030\002 \002(\t\022\021\n\tchunkData\030\003 \002(\014\"\311\001" +
      "\n\017ICChunkRecovery\022\r\n\005appID\030\001 \002(\t\022\013\n\003cid\030" +
      "\002 \002(\005\022\017\n\007chunkId\030\003 \002(\005\022\021\n\tchunkData\030\004 \002(" +
      "\014\022:\n\tsignature\030\005 \003(\0132\'.ICChunkRecovery.O" +
      "wnerAndSignatureTuple\032:\n\026OwnerAndSignatu" +
      "reTuple\022\r\n\005owner\030\001 \002(\005\022\021\n\tsignature\030\002 \002(" +
      "\014B)\n\027gr.uoa.di.dsg.ic.brachaB\016ICDatumMes" +
      "sage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ICChunk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ICChunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ICChunk_descriptor,
        new java.lang.String[] { "ChunkId", "AppID", "ChunkData", });
    internal_static_ICChunkRecovery_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ICChunkRecovery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ICChunkRecovery_descriptor,
        new java.lang.String[] { "AppID", "Cid", "ChunkId", "ChunkData", "Signature", });
    internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor =
      internal_static_ICChunkRecovery_descriptor.getNestedTypes().get(0);
    internal_static_ICChunkRecovery_OwnerAndSignatureTuple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ICChunkRecovery_OwnerAndSignatureTuple_descriptor,
        new java.lang.String[] { "Owner", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
